[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/*" # Apply to your sensitive paths
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, private"
    Pragma = "no-cache"
    Expires = "0"
