import type { Metadata } from "next";
import StyledComponentsRegistry from "../../public/lib/registry";
import { ThemeProvider } from "@/UI/Global/ThemeProvider";
import "@/UI/Global/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <ThemeProvider>{children}</ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
