import { BERRY, ORANGE, PINK, GREEN, BLUE } from "../../data";
import type { Resource } from "../../types";

export interface ExtendedResource extends Resource {
  releaseDate?: string;
  releaseTimestamp?: number;
  stage?: string;
}

export interface TransitionStage {
  id: string;
  number: number;
  label: string;
  shortLabel: string;
  description: string;
  accentColor: string;
}

export const TRANSITION_STAGES: TransitionStage[] = [
  {
    id: "stage1",
    number: 1,
    label: "Exploration & Orientation",
    shortLabel: "Exploration",
    description: "Is tech right for me? Get grounded in realistic expectations, myth-busting, and the roles available to you.",
    accentColor: PINK,
  },
  {
    id: "stage2",
    number: 2,
    label: "Asset Building & Language",
    shortLabel: "Asset Building",
    description: "Translate your background into tech-ready language, jargon, and a compelling personal story.",
    accentColor: BERRY,
  },
  {
    id: "stage3",
    number: 3,
    label: "Job Hunting & Outreach",
    shortLabel: "Job Hunting",
    description: "Get visible, network with intention, and land (and win) interviews.",
    accentColor: BLUE,
  },
  {
    id: "stage4",
    number: 4,
    label: "Resilience & Reality",
    shortLabel: "Resilience",
    description: "Stay mentally strong on the job and navigate the unspoken realities of tech culture.",
    accentColor: GREEN,
  },
];

export const RESOURCE_CATEGORIES = [
  "All",
  "Mindset & Fundamentals",
  "Myth Busting",
  "Career Paths",
  "Action Plan",
  "Terminology",
  "Resume & Strategy",
  "Networking",
  "Interviewing",
  "Insider Realities",
];

export const LAUNCH_DATE = "2026-09-14";
const LAUNCH_TIMESTAMP = new Date(`${LAUNCH_DATE}T00:00:00Z`).getTime();
const LAUNCH_DATE_LABEL = "Sep 14, 2026";

export const DEFAULT_RESOURCES: ExtendedResource[] = [
  {
    id: "guide-1",
    title: "10 Things to Know When Transitioning into Tech",
    slug: "10-things-to-know-transitioning-into-tech",
    description: "Essential foundational advice for absolute beginners. Learn why problem-solving beats memorizing code, how to leverage non-tech skills, and how to stay consistent.",
    category: "Mindset & Fundamentals",
    stage: "stage1",
    pdfUrl: "/unlock-her-tech-career-plan-september-19-2026.pdf",
    fileSize: "3 Pages • Printable PDF",
    pageCount: "3 Pages",
    accentColor: PINK,
    isPublished: true,
    publishedAt: LAUNCH_DATE,
    releaseDate: LAUNCH_DATE_LABEL,
    releaseTimestamp: LAUNCH_TIMESTAMP,
    weekNumber: 1,
    requiresLogin: false,
  },
  {
    id: "guide-2",
    title: "10 Myths About the Tech Industry (Debunked)",
    slug: "10-myths-about-tech-industry-debunked",
    description: "Separating fact from fiction for career changers. Bust common rumors regarding CS degrees, math requirements, age limits, and bootcamp promises.",
    category: "Myth Busting",
    stage: "stage1",
    pdfUrl: "/unlock-her-tech-career-plan-september-19-2026.pdf",
    fileSize: "3 Pages • Printable PDF",
    pageCount: "3 Pages",
    accentColor: BLUE,
    isPublished: true,
    publishedAt: LAUNCH_DATE,
    releaseDate: LAUNCH_DATE_LABEL,
    releaseTimestamp: LAUNCH_TIMESTAMP,
    weekNumber: 2,
    requiresLogin: false,
  },
  {
    id: "guide-3",
    title: "10 Non-Coding Roles in Tech to Explore",
    slug: "10-non-coding-roles-in-tech",
    description: "Discover high-impact software careers that don't require writing code. Breakdown of PM, UX/UI Design, Technical Writing, DevRel, Data, and Scrum.",
    category: "Career Paths",
    stage: "stage1",
    pdfUrl: "/unlock-her-tech-career-plan-september-19-2026.pdf",
    fileSize: "3 Pages • Printable PDF",
    pageCount: "3 Pages",
    accentColor: GREEN,
    isPublished: true,
    publishedAt: LAUNCH_DATE,
    releaseDate: LAUNCH_DATE_LABEL,
    releaseTimestamp: LAUNCH_TIMESTAMP,
    weekNumber: 3,
    requiresLogin: false,
  },
  {
    id: "guide-4",
    title: "10-Step Action Roadmap: From Beginner to Hired",
    slug: "10-step-action-roadmap-beginner-to-hired",
    description: "A step-by-step master sequence covering learning, projects, networking, applications, and offers, mapped across the full transition journey.",
    category: "Action Plan",
    stage: "stage1",
    pdfUrl: "/unlock-her-tech-career-plan-september-19-2026.pdf",
    fileSize: "3 Pages • Printable PDF",
    pageCount: "3 Pages",
    accentColor: ORANGE,
    isPublished: true,
    publishedAt: LAUNCH_DATE,
    releaseDate: LAUNCH_DATE_LABEL,
    releaseTimestamp: LAUNCH_TIMESTAMP,
    weekNumber: 4,
    requiresLogin: true,
  },
  {
    id: "guide-5",
    title: "10 Essential Tech Jargon Terms Decoded",
    slug: "10-essential-tech-jargon-terms-decoded",
    description: "Demystify APIs, Tech Debt, Agile, CI/CD, Standups, MVP, and Refactoring in plain English so you can speak the language on day one.",
    category: "Terminology",
    stage: "stage2",
    pdfUrl: "/unlock-her-tech-career-plan-september-19-2026.pdf",
    fileSize: "3 Pages • Printable PDF",
    pageCount: "3 Pages",
    accentColor: BERRY,
    isPublished: true,
    publishedAt: LAUNCH_DATE,
    releaseDate: LAUNCH_DATE_LABEL,
    releaseTimestamp: LAUNCH_TIMESTAMP,
    weekNumber: 5,
    requiresLogin: true,
  },
  {
    id: "guide-6",
    title: "10 Ways to Translate Your Transferable Skills",
    slug: "10-ways-to-translate-transferable-skills",
    description: "Reframe non-tech experience from teaching, sales, retail, or healthcare into tech accomplishments that hiring managers love.",
    category: "Resume & Strategy",
    stage: "stage2",
    pdfUrl: "/unlock-her-tech-career-plan-september-19-2026.pdf",
    fileSize: "3 Pages • Printable PDF",
    pageCount: "3 Pages",
    accentColor: ORANGE,
    isPublished: true,
    publishedAt: LAUNCH_DATE,
    releaseDate: LAUNCH_DATE_LABEL,
    releaseTimestamp: LAUNCH_TIMESTAMP,
    weekNumber: 6,
    requiresLogin: true,
  },
  {
    id: "guide-7",
    title: "10 Networking & LinkedIn Strategies for Tech Job Seekers",
    slug: "10-networking-linkedin-strategies-tech-job-seekers",
    description: "Optimize your headline, pin a Loom video walkthrough, request informational chats, and land referrals from real tech professionals.",
    category: "Networking",
    stage: "stage3",
    pdfUrl: "/unlock-her-tech-career-plan-september-19-2026.pdf",
    fileSize: "3 Pages • Printable PDF",
    pageCount: "3 Pages",
    accentColor: PINK,
    isPublished: true,
    publishedAt: LAUNCH_DATE,
    releaseDate: LAUNCH_DATE_LABEL,
    releaseTimestamp: LAUNCH_TIMESTAMP,
    weekNumber: 7,
    requiresLogin: true,
  },
  {
    id: "guide-8",
    title: "10 Technical & Behavioral Interview Hacks for Beginners",
    slug: "10-technical-behavioral-interview-hacks-beginners",
    description: "Master the STAR method, think out loud during live coding, and ask high-leverage questions that make you memorable.",
    category: "Interviewing",
    stage: "stage3",
    pdfUrl: "/unlock-her-tech-career-plan-september-19-2026.pdf",
    fileSize: "3 Pages • Printable PDF",
    pageCount: "3 Pages",
    accentColor: BLUE,
    isPublished: true,
    publishedAt: LAUNCH_DATE,
    releaseDate: LAUNCH_DATE_LABEL,
    releaseTimestamp: LAUNCH_TIMESTAMP,
    weekNumber: 8,
    requiresLogin: true,
  },
  {
    id: "guide-9",
    title: "10 Mental Health & Mindset Strategies for Tech",
    slug: "10-mental-health-mindset-strategies-tech",
    description: "Beat imposter syndrome, avoid comparison traps, build a 'wins' document, and protect your boundaries against burnout.",
    category: "Mindset & Fundamentals",
    stage: "stage4",
    pdfUrl: "/unlock-her-tech-career-plan-september-19-2026.pdf",
    fileSize: "3 Pages • Printable PDF",
    pageCount: "3 Pages",
    accentColor: GREEN,
    isPublished: true,
    publishedAt: LAUNCH_DATE,
    releaseDate: LAUNCH_DATE_LABEL,
    releaseTimestamp: LAUNCH_TIMESTAMP,
    weekNumber: 9,
    requiresLogin: true,
  },
  {
    id: "guide-10",
    title: "10 Pet Peeves & Unspoken Realities of Tech",
    slug: "10-pet-peeves-unspoken-realities-tech",
    description: "Unfiltered, honest insights into everyday workplace culture. Navigate legacy code, meeting fatigue, shifting product scopes, and time estimation.",
    category: "Insider Realities",
    stage: "stage4",
    pdfUrl: "/unlock-her-tech-career-plan-september-19-2026.pdf",
    fileSize: "3 Pages • Printable PDF",
    pageCount: "3 Pages",
    accentColor: ORANGE,
    isPublished: true,
    publishedAt: LAUNCH_DATE,
    releaseDate: LAUNCH_DATE_LABEL,
    releaseTimestamp: LAUNCH_TIMESTAMP,
    weekNumber: 10,
    requiresLogin: true,
  },
];
