import { BERRY, ORANGE, PINK, GREEN, BLUE } from "../../data";
import type { Resource } from "../../types";

export interface ExtendedResource extends Resource {
  releaseDate?: string;
  releaseTimestamp?: number;
}

export const RESOURCE_CATEGORIES = [
  "All",
  "Mindset & Fundamentals",
  "Myth Busting",
  "Insider Realities",
  "Career Paths",
  "Resume & Strategy",
];

export const DEFAULT_WEEKLY_RESOURCES: ExtendedResource[] = [
  {
    id: "guide-1",
    title: "10 Things to Know When Transitioning into Tech",
    slug: "10-things-to-know-transitioning-into-tech",
    description: "Essential foundational advice for absolute beginners. Learn why problem-solving beats memorizing code, how to leverage non-tech skills, and how to stay consistent.",
    category: "Mindset & Fundamentals",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    fileSize: "3 Pages • Printable PDF",
    pageCount: "3 Pages",
    accentColor: PINK,
    isPublished: true,
    publishedAt: "2026-09-07",
    releaseDate: "Sep 7, 2026",
    releaseTimestamp: new Date("2026-09-07T00:00:00Z").getTime(),
    weekNumber: 1,
    requiresLogin: false,
  },
  {
    id: "guide-2",
    title: "10 Myths About the Tech Industry (Debunked)",
    slug: "10-myths-about-tech-industry-debunked",
    description: "Separating fact from fiction for career changers. Bust common rumors regarding CS degrees, math requirements, age limits, and bootcamp promises.",
    category: "Myth Busting",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    fileSize: "3 Pages • Printable PDF",
    pageCount: "3 Pages",
    accentColor: BLUE,
    isPublished: true,
    publishedAt: "2026-09-14",
    releaseDate: "Sep 14, 2026",
    releaseTimestamp: new Date("2026-09-14T00:00:00Z").getTime(),
    weekNumber: 2,
    requiresLogin: false,
  },
  {
    id: "guide-3",
    title: "10 Pet Peeves & Unspoken Realities of Tech",
    slug: "10-pet-peeves-unspoken-realities-tech",
    description: "Unfiltered, honest insights into everyday workplace culture. Navigate legacy code, meeting fatigue, shifting product scopes, and setting boundaries.",
    category: "Insider Realities",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    fileSize: "3 Pages • Printable PDF",
    pageCount: "3 Pages",
    accentColor: ORANGE,
    isPublished: true,
    publishedAt: "2026-09-21",
    releaseDate: "Sep 21, 2026",
    releaseTimestamp: new Date("2026-09-21T00:00:00Z").getTime(),
    weekNumber: 3,
    requiresLogin: false,
  },
  {
    id: "guide-4",
    title: "10 Non-Coding Roles in Tech to Explore",
    slug: "10-non-coding-roles-in-tech",
    description: "Discover high-impact software careers that don't require writing code. Breakdown of PM, UX/UI Design, Technical Writing, DevRel, Data, and Scrum.",
    category: "Career Paths",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    fileSize: "4 Pages • Printable PDF",
    pageCount: "4 Pages",
    accentColor: GREEN,
    isPublished: true,
    publishedAt: "2026-09-28",
    releaseDate: "Sep 28, 2026",
    releaseTimestamp: new Date("2026-09-28T00:00:00Z").getTime(),
    weekNumber: 4,
    requiresLogin: true,
  },
  {
    id: "guide-5",
    title: "10 Ways to Translate Your Transferable Skills",
    slug: "10-ways-to-translate-transferable-skills",
    description: "Reframe non-tech experience from teaching, sales, retail, or healthcare into tech accomplishments that hiring managers love.",
    category: "Resume & Strategy",
    pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    fileSize: "3 Pages • Printable PDF",
    pageCount: "3 Pages",
    accentColor: BERRY,
    isPublished: true,
    publishedAt: "2026-10-05",
    releaseDate: "Oct 5, 2026",
    releaseTimestamp: new Date("2026-10-05T00:00:00Z").getTime(),
    weekNumber: 5,
    requiresLogin: true,
  },
];
